//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aladdin.CAPI.GUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aladdin.CAPI.GUI.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto API Administration Console.
        /// </summary>
        internal static string CommonName {
            get {
                return ResourceManager.GetString("CommonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered passwords mismatch.
        /// </summary>
        internal static string ErrorPasswordMismatch {
            get {
                return ResourceManager.GetString("ErrorPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Path Length.
        /// </summary>
        internal static string ErrorPathLength {
            get {
                return ResourceManager.GetString("ErrorPathLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate public key is not the container public key.
        /// </summary>
        internal static string ErrorPublicKeyMismatch {
            get {
                return ResourceManager.GetString("ErrorPublicKeyMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Subject Name.
        /// </summary>
        internal static string ErrorSubjectName {
            get {
                return ResourceManager.GetString("ErrorSubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.509 Files (*.cer)|*.cer.
        /// </summary>
        internal static string FilterCertificateFile {
            get {
                return ResourceManager.GetString("FilterCertificateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKCS10 Files (*.p10)|*.p10.
        /// </summary>
        internal static string FilterRequestFile {
            get {
                return ResourceManager.GetString("FilterRequestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language for display....
        /// </summary>
        internal static string MenuChangeLanguage {
            get {
                return ResourceManager.GetString("MenuChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change authentication data....
        /// </summary>
        internal static string MenuChangeLogin {
            get {
                return ResourceManager.GetString("MenuChangeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create selfsigned certificate....
        /// </summary>
        internal static string MenuCreateCertificate {
            get {
                return ResourceManager.GetString("MenuCreateCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create certificate request....
        /// </summary>
        internal static string MenuCreateRequest {
            get {
                return ResourceManager.GetString("MenuCreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete container.
        /// </summary>
        internal static string MenuDeleteContainer {
            get {
                return ResourceManager.GetString("MenuDeleteContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete key pair.
        /// </summary>
        internal static string MenuDeleteKeyPair {
            get {
                return ResourceManager.GetString("MenuDeleteKeyPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate container key pair....
        /// </summary>
        internal static string MenuGenerateKeyPair {
            get {
                return ResourceManager.GetString("MenuGenerateKeyPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import container key pair....
        /// </summary>
        internal static string MenuImportKeyPair {
            get {
                return ResourceManager.GetString("MenuImportKeyPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage container directories....
        /// </summary>
        internal static string MenuManageDirectories {
            get {
                return ResourceManager.GetString("MenuManageDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string MenuProperties {
            get {
                return ResourceManager.GetString("MenuProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set certificate....
        /// </summary>
        internal static string MenuSetCertificate {
            get {
                return ResourceManager.GetString("MenuSetCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show container.
        /// </summary>
        internal static string MenuShowContainer {
            get {
                return ResourceManager.GetString("MenuShowContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View container certificates.
        /// </summary>
        internal static string MenuViewCertificates {
            get {
                return ResourceManager.GetString("MenuViewCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication data is successfully changed.
        /// </summary>
        internal static string MessageChangeLogin {
            get {
                return ResourceManager.GetString("MessageChangeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger template is done. Leave finger out of scaner.
        /// </summary>
        internal static string MessageFingerCaptured {
            get {
                return ResourceManager.GetString("MessageFingerCaptured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The finger template is not verified.
        /// </summary>
        internal static string MessageFingerEnrollNoVerified {
            get {
                return ResourceManager.GetString("MessageFingerEnrollNoVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The finger template is verified.
        /// </summary>
        internal static string MessageFingerEnrollVerified {
            get {
                return ResourceManager.GetString("MessageFingerEnrollVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The finger capture image has low quality.
        /// </summary>
        internal static string MessageFingerQuality {
            get {
                return ResourceManager.GetString("MessageFingerQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger template is done. Leave finger out of scaner and then touch finger again to scanner for verification.
        /// </summary>
        internal static string MessageFingerRepeat {
            get {
                return ResourceManager.GetString("MessageFingerRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch finger to scanner.
        /// </summary>
        internal static string MessageFingerTouch {
            get {
                return ResourceManager.GetString("MessageFingerTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The finger templates are successfully verified.
        /// </summary>
        internal static string MessageFingerVerifyCompleted {
            get {
                return ResourceManager.GetString("MessageFingerVerifyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Types.
        /// </summary>
        internal static string NodeCardTypes {
            get {
                return ResourceManager.GetString("NodeCardTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providers.
        /// </summary>
        internal static string NodeProviders {
            get {
                return ResourceManager.GetString("NodeProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readers.
        /// </summary>
        internal static string NodeReaders {
            get {
                return ResourceManager.GetString("NodeReaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete selected object(s)?.
        /// </summary>
        internal static string QuestionDeleteObjects {
            get {
                return ResourceManager.GetString("QuestionDeleteObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The container directories are successfully changed.
        /// </summary>
        internal static string StatusChangeDirectories {
            get {
                return ResourceManager.GetString("StatusChangeDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The container(s) is successfully deleted.
        /// </summary>
        internal static string StatusDeleteContainers {
            get {
                return ResourceManager.GetString("StatusDeleteContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key pair(s) is successfully deleted.
        /// </summary>
        internal static string StatusDeleteKeyPairs {
            get {
                return ResourceManager.GetString("StatusDeleteKeyPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key pair is successfully generated.
        /// </summary>
        internal static string StatusGeneratePair {
            get {
                return ResourceManager.GetString("StatusGeneratePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key pair is successfully imported.
        /// </summary>
        internal static string StatusImportPair {
            get {
                return ResourceManager.GetString("StatusImportPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate request is successfully save to file.
        /// </summary>
        internal static string StatusSaveRequestFile {
            get {
                return ResourceManager.GetString("StatusSaveRequestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate is successfully set.
        /// </summary>
        internal static string StatusSetCertificate {
            get {
                return ResourceManager.GetString("StatusSetCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select container directory:.
        /// </summary>
        internal static string TitleDialogDirectory {
            get {
                return ResourceManager.GetString("TitleDialogDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select certificate file.
        /// </summary>
        internal static string TitleOpenCertificateFile {
            get {
                return ResourceManager.GetString("TitleOpenCertificateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file for certificate request.
        /// </summary>
        internal static string TitleSaveRequestFile {
            get {
                return ResourceManager.GetString("TitleSaveRequestFile", resourceCulture);
            }
        }
    }
}
